blogbyflask/web/forms/__init__.py
from .post import PostForm


__all__ = [
    "PostForm"
]

blogbyflask/web/forms/post.py
from wtforms import fields, widgets
from flask_wtf import FlaskForm
from flask_mongoengine.wtf import model_form
from blogbyflask import models



class PostForm(FlaskForm):
    title = fields.StringField("ชื่อหัวข้อ")
    subtitle = fields.StringField("เรื่องย่อ")
    author = fields.StringField("ชื่อผู้เขียน")
    content = fields.StringField("content")
    upload_picture = fields.FileField("รูปภาพประกอบ")
    

blogbyflask/web/__init__.py
import optparse

from flask import Flask

from .. import models
from . import views
from . import acl

app = Flask(__name__)


def create_app():
    app.config.from_object("blogbyflask.default_settings")
    app.config.from_envvar(
        "BLOGBYFLASK_SETTINGS", silent=True
    )

    models.init_db(app)
    views.register_blueprint(app)
    acl.init_acl(app)

    return app


def get_program_options(default_host="127.0.0.1", default_port="8080"):

    """
    Takes a flask.Flask instance and runs it. Parses
    command-line flags to configure the app.
    """

    # Set up the command-line options
    parser = optparse.OptionParser()
    parser.add_option(
        "-H",
        "--host",
        help="Hostname of the Flask app " + "[default %s]" % default_host,
        default=default_host,
    )
    parser.add_option(
        "-P",
        "--port",
        help="Port for the Flask app " + "[default %s]" % default_port,
        default=default_port,
    )

    # Two options useful for debugging purposes, but
    # a bit dangerous so not exposed in the help message.
    parser.add_option(
        "-c", "--config", dest="config", help=optparse.SUPPRESS_HELP, default=None
    )
    parser.add_option(
        "-d", "--debug", action="store_true", dest="debug", help=optparse.SUPPRESS_HELP
    )
    parser.add_option(
        "-p",
        "--profile",
        action="store_true",
        dest="profile",
        help=optparse.SUPPRESS_HELP,
    )

    options, _ = parser.parse_args()

    # If the user selects the profiling option, then we need
    # to do a little extra setup
    if options.profile:
        from werkzeug.middleware.profiler import ProfilerMiddleware

        app.config["PROFILE"] = True
        app.wsgi_app = ProfilerMiddleware(app.wsgi_app, restrictions=[30])
        options.debug = True

    return options

blogbyflask/web/views/__init__.py
from . import add, sites
import datetime
from flask import redirect, url_for


def add_date_url(url):
    now = datetime.datetime.now()
    return f'{url}?date={now.strftime("%Y%m%d")}'


def get_subblueprints(views=[]):
    blueprints = []
    for view in views:
        blueprints.append(view.module)
        if "subviews" in dir(view):
            for module in get_subblueprints(view.subviews):
                if view.module.url_prefix and module.url_prefix:
                    module.url_prefix = view.module.url_prefix + module.url_prefix
                blueprints.append(module)
    return blueprints


def register_blueprint(app):
    app.add_template_filter(add_date_url)
    blueprints = get_subblueprints(
        [
            add,
            sites
        ]
    )

    for blueprint in blueprints:
        app.register_blueprint(blueprint)

    

blogbyflask/web/views/add.py
from flask import (
    Blueprint,
    redirect,
    render_template,
    url_for,
    redirect,
    Response,
    send_file,
    request,
)

from datetime import datetime
from blogbyflask import models
from blogbyflask.web import forms


module = Blueprint("accounts", __name__, url_prefix="/accounts")

@module.route("/add", methods=["GET","POST"])
def add():
    form = forms.PostForm()
    if not form.validate_on_submit():
        return render_template(
            "post/addPost.html",
                            form=form,
        )
    
    post = models.Post()
    if form.upload_picture.data:
        data = form.upload_picture.data
        post.picture.put(data, filename=data.filename, content_type=data.content_type)
    post.title = form.title.data 
    post.subtitle = form.subtitle.data 
    post.author = form.author.data 
    post.content = form.content.data 
    post.created_date = datetime.now()
    post.save()

    return redirect(
        url_for(
            "sites.index",
        )
    )



@module.route("/<post_id>/edit", methods=["GET","POST"])
def edit(post_id):
    post = models.Post.objects.get(id=post_id)
    form = forms.PostForm(obj=post)


    if not form.validate_on_submit():
        return render_template(
            "post/addPost.html",
            post=post,
                            form=form,
        )

    if form.upload_picture.data:
        data = form.upload_picture.data
        if post.picture:
            post.picture.replace(
                data, filename=data.filename, content_type=data.content_type
            )
        else:
            post.picture.put(
                data, filename=data.filename, content_type=data.content_type
            )

    form.populate_obj(post)
    post.save()
    return redirect(
        url_for(
            "sites.index",
        )
    )

@module.route("/get_image/<post_id>/<filename>/<get_type>", methods=["GET", "POST"])
def get_image(post_id, filename, get_type):
    post = models.Post.objects.get(id=post_id)
    img = None
    if post.picture.filename == filename:
        if get_type == "thumbnail":
            img = post.picture.thumbnail
        else:
            img = post.picture
    response = Response()
    if img:
        mimetype = "image/jpg"
        if hasattr(img, "content_type") and img.content_type:
            mimetype = img.content_type
        elif hasattr(img, "filename") and img.filename:
            mimetype = "image/{}".format(img.filename[: img.filename.rfind(".")])
        mimetype = mimetype.lower()
        response = send_file(img, mimetype=mimetype)
    else:
        response.status_code = 404
    return response


@module.route("/<post_id>/delete", methods=["GET", "POST"])
def delete(post_id):
    post = models.Post.objects.get(id=post_id)
    post.delete()

    return redirect(
        url_for(
            "sites.index",
        )
    )

@module.route("/<post_id>/read", methods=["GET", "POST"])
def read(post_id):
    post = models.Post.objects.get(id=post_id)
    return render_template(
        "sites/readnow.html",
        post=post
        )

blogbyflask/web/views/sites.py
from flask import (Blueprint , render_template)
from blogbyflask import models
from blogbyflask.web import forms


# set module = sites
module = Blueprint("sites", __name__)



@module.route("/")
def index():
    post = models.Post.objects().order_by("-id")

    return render_template(
        "sites/index.html",
        post=post
        )

blogbyflask/web/templates/base/default-page.html
{% block body %}

{% include "base/navbar.html" %}

<main>
  <link rel="stylesheet" type="text/css" media="all" href="{{ url_for('static', filename='css/style.css') }}">
  

  {% block content %}{% endblock content %}
</main>
<!-- footer -->
{% include "base/footer.html" %}

{% endblock %}

blogbyflask/web/templates/base/footer.html
<footer class="border-top">
  <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <ul class="list-inline text-center">
                  <li class="list-inline-item">
                      <a href="#!">
                          <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                          </span>
                      </a>
                  </li>
                  <li class="list-inline-item">
                      <a href="#!">
                          <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                          </span>
                      </a>
                  </li>
                  <li class="list-inline-item">
                      <a href="#!">
                          <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                          </span>
                      </a>
                  </li>
              </ul>
              <div class="small text-center text-muted fst-italic">Copyright &copy; flask</div>
          </div>
      </div>
  </div>
</footer>

blogbyflask/web/templates/base/navbar.html
<!-- Nav Bar -->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="/">BlogbyFlask</a>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a></li>
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">About</a></li>
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('accounts.add' ) }}">Add</a></li>
      </ul>
    </div>
  </div>
</nav>

blogbyflask/web/templates/post/addPost.html
<link rel="stylesheet" type="text/css" media="all" href="{{ url_for('static', filename='css/style.css') }}">
{% extends "base/default-page.html" %}

{% block content %}
<!-- Page Header -->
<header class="masthead">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>ADDPOST</h1>
          <span class="subheading">A Blog by TS</span>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}

    <div class="col mb-3">
      {{ form.title.label }}
      {{ form.title }}
    </div>
    <div class="col mb-3">
      {{ form.subtitle.label }}
      {{ form.subtitle}}
    </div>
    <div class="col mb-3">
      {{ form.author.label }}
      {{ form.author }}
    </div>
    <div class="col mb-3">
      {{ form.content.label }}
      {{ form.content}}
    </div>
    <div class="col mb-3">
      {{ form.upload_picture.label }}
      {{ form.upload_picture(class="form-control custom-file-button", onchange="loadFile(event)", type="file",
      accept="image/*") }}
    </div>
    
    <img class="mt-3" id='output' style="width: auto; height: 360px; border-radius: 1rem;"
    {% if 'edit' in request.path and post.picture %}
      src="{{ url_for('accounts.get_image', post_id=post.id, filename=post.picture.filename, get_type='thumbnail') }}"
    {% endif %}>

    <div class="center">
      <button name="create" type="submit" class="btn btn-primary" justify-content="center">
        {% if 'edit' in request.path %}

        edit

        {%endif%}
        {% if 'add' in request.path %}

        add
        {%endif%}
      </button>
    </div>
</div>


</form>
{% endblock %}

blogbyflask/web/templates/sites/index.html
{% extends "base/default-page.html" %}

{% block content %}
<!-- Page Header -->
<header class="masthead">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-1 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-5 col-xl-7">
        <div class="site-heading">
          <h1>BlogbyFlask</h1>
          <span class="subheading">A Blog by TS</span>
        </div>
      </div>
    </div>
  </div>
</header>


{%for i in post %}
<article class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h2 class="section-heading">{{i.title }}</h2>
        <h5>{{i.author }}</h5>
        <blockquote class="blockquote">{{i.subtitle }}</blockquote>
      </div>
      <div class="card-body">
        <a class="btn btn-primary" style="float: left" aria-current="page"
          href="{{ url_for('accounts.read', post_id=i.id) }}">
          read
        </a>
        <a class="btn btn-danger" style="float: right" aria-current="page"
          href="{{ url_for('accounts.delete', post_id=i.id) }}">
          delete
        </a>
        <a class="btn btn-primary" style="float: right" aria-current="page"
          href="{{ url_for('accounts.edit', post_id=i.id) }}">
          edit
        </a>

      </div>
    </div>
    <hr>
</article>



</div>
{%endfor%}




<style>
  .card {
    /* Add shadows to create the "card" effect */
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    transition: 0.3s;
  }

  /* On mouse-over, add a deeper shadow */
  .card:hover {
    box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
  }

  /* Add some padding inside the card container */
  .container {
    padding: 2px 16px;
  }
</style>
{% endblock %}

blogbyflask/web/templates/sites/readnow.html
{% extends "base/default-page.html" %}

{% block content %}
<!-- Page Header -->
<header class="masthead">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-1 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-5 col-xl-7">
                <div class="site-heading">
                    <h1>BlogbyFlask</h1>
                    <span class="subheading">A Blog by TS</span>
                </div>
            </div>
        </div>
    </div>
</header>


<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h2 class="section-heading">{{post.title }}</h2>
                <h5> author {{post.author }}</h5>
                <h6> create {{post.created_date.strftime('%d-%m-%Y')}} </h6>
                {% if post.picture %}
                <img src="{{ url_for('accounts.get_image', post_id=post.id, filename=post.picture.filename, get_type='thumbnail') }}"
                    class="img-fluid rounded-3 mx-auto" alt="cover-image">
                {% endif %}
                <blockquote class="blockquote">{{post.subtitle }}</blockquote>
                <p>{{post.content}}</p>
            </div>

        </div>
        <hr>
</article>



<style>
    .card {
        /* Add shadows to create the "card" effect */
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        transition: 0.3s;
    }

    /* On mouse-over, add a deeper shadow */
    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
    }

    /* Add some padding inside the card container */
    .container {
        padding: 2px 16px;
    }
</style>
{% endblock %}